name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: first-name
          - name: second-name
    outputs:
      ${{ matrix.name }}: ${{ steps.step1.outputs.the-out }}
    steps:
    - id: step1
      run: echo "the-out=${{matrix.app.name}}" >> "$GITHUB_OUTPUT"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
    - run: |
        #echo "${{ needs.first-job[0].outputs.the-out }}"
        echo "${{ needs.first-job.outputs.first-name }}"
